apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-was
spec:
  replicas: 0
  selector:
    matchLabels:
      app: petclinic-was
  template:
    metadata:
      labels:
        app: petclinic-was
    spec:
      containers:
        - name: petclinic-was
          image: 620832535900.dkr.ecr.ap-northeast-2.amazonaws.com/was:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m
          env:
            - name: jdbc.url
              valueFrom:
                secretKeyRef:
                  name: petclinic-db
                  key: jdbc.url
            - name: jdbc.username
              valueFrom:
                secretKeyRef:
                  name: petclinic-db
                  key: jdbc.username
            - name: jdbc.password
              valueFrom:
                secretKeyRef:
                  name: petclinic-db
                  key: jdbc.password
